#!/bin/sh

fatal()
{
  echo "fatal: $1" 1>&2
  exit 1
}

if [ $# -ne 2 ]
then
  fatal "usage: output.o file.c"
fi

CONF_OUTPUT="$1"
shift
CONF_SOURCE="$1"
shift

CONF_CC=$(head -n 1 conf-c-compile) || fatal "could not read conf-c-compile"
CONF_CFLAGS=$(egrep -v '^#' conf-c-flags) || fatal "could not read conf-c-flags"

mkdir -p $(dirname "${CONF_OUTPUT}") || fatal "could not create output directory"

exec ${CONF_CC} -c ${CONF_CFLAGS} -o "${CONF_OUTPUT}" "${CONF_SOURCE}"
